/*
  GERADO a partir da pasta imagens/ do próprio repositório.

  O poneis.js casa cada entrada com o pônei pelo nome normalizado
  (sem acento, sem espaço, minúsculo). Quem não tiver imagem aqui
  continua sendo desenhado em SVG — nada quebra pela metade.

  Fora da lista de propósito: versões Equestria Girls (humanas),
  capas de episódio, grupos e imagens com duas personagens juntas.
*/
const PERSONAGENS = [
  { nome: "Amber Waves",            img: "imagens/Amber Waves.png" },
  { nome: "Amethyst Maresbury",     img: "imagens/Amethyst Maresbury.png" },
  { nome: "Amethyst Star",          img: "imagens/Amethyst Star.png" },
  { nome: "Apple Bloom",            img: "imagens/Apple Bloom.png" },
  { nome: "Apple Brown Betty",      img: "imagens/Apple Brown Betty.png" },
  { nome: "Apple Bumpkin",          img: "imagens/Apple Bumpkin.png" },
  { nome: "Apple Cinnamon",         img: "imagens/Apple Cinnamon.png" },
  { nome: "Apple Cobbler",          img: "imagens/Apple Cobbler.png" },
  { nome: "Apple Fritter",          img: "imagens/Apple Fritter.png" },
  { nome: "Apple Honey",            img: "imagens/Apple Honey.png" },
  { nome: "Apple Rose",             img: "imagens/Apple Rose.png" },
  { nome: "Apple Strudel",          img: "imagens/Apple Strudel.png" },
  { nome: "Asno Azedo Simplório",   img: "imagens/Asno Azedo Simplório.png" },
  { nome: "Babs Seed",              img: "imagens/Babs Seed.png" },
  { nome: "Big McIntosh",           img: "imagens/Big McIntosh.png" },
  { nome: "Blaze",                  img: "imagens/Blaze.png" },
  { nome: "Blossomforth",           img: "imagens/Blossomforth.png" },
  { nome: "Bright Smile",           img: "imagens/Bright Smile.png" },
  { nome: "Bulk Biceps",            img: "imagens/Bulk Biceps.png" },
  { nome: "Candy Mane",             img: "imagens/Candy Mane.png" },
  { nome: "Capitã Selena",          img: "imagens/Capitã Selena.png" },
  { nome: "Caramel Apple",          img: "imagens/Caramel Apple.png" },
  { nome: "Charm",                  img: "imagens/Charm.png" },
  { nome: "Cheerilee",              img: "imagens/Cheerilee.png" },
  { nome: "Cheese Sandwich",        img: "imagens/Cheese Sandwich.png" },
  { nome: "Cherry Berry",           img: "imagens/Cherry Berry.png" },
  { nome: "Cherry Fizzy",           img: "imagens/Cherry Fizzy.png" },
  { nome: "Cherry Jubilee",         img: "imagens/Cherry Jubilee.png" },
  { nome: "Claude",                 img: "imagens/Claude.png" },
  { nome: "Cloud Kicker",           img: "imagens/Cloud Kicker.png" },
  { nome: "Coco Crusoe",            img: "imagens/Coco Crusoe.png" },
  { nome: "Coco Pommel",            img: "imagens/Coco Pommel.png" },
  { nome: "Comet Tail",             img: "imagens/Comet Tail.png" },
  { nome: "Compass Star",           img: "imagens/Compass Star.png" },
  { nome: "Crescent Moon",          img: "imagens/Crescent Moon.png" },
  { nome: "Crystal Arrow",          img: "imagens/Crystal Arrow.png" },
  { nome: "DJ Pon-3",               img: "imagens/DJ Pon-3.png" },
  { nome: "Daisy",                  img: "imagens/Daisy.png" },
  { nome: "Daring Do (personagem)", img: "imagens/Daring Do (personagem).png" },
  { nome: "Dark Moon",              img: "imagens/Dark Moon.png" },
  { nome: "Davenport",              img: "imagens/Davenport.png" },
  { nome: "Diamond Mint",           img: "imagens/Diamond Mint.png" },
  { nome: "Diamond Tiara",          img: "imagens/Diamond Tiara.png" },
  { nome: "Discórdia",              img: "imagens/Discórdia.png" },
  { nome: "Double Diamond",         img: "imagens/Double Diamond.png" },
  { nome: "Doutor Horse",           img: "imagens/Doutor Horse.png" },
  { nome: "Dr. Caballeron",         img: "imagens/Dr. Caballeron.png" },
  { nome: "Dr. Hooves",             img: "imagens/Dr. Hooves.png" },
  { nome: "Eclair Crème",           img: "imagens/Eclair Crème.png" },
  { nome: "Elbow Grease",           img: "imagens/Elbow Grease.png" },
  { nome: "Emerald Green",          img: "imagens/Emerald Green.png" },
  { nome: "Enfermeira Redheart",    img: "imagens/Enfermeira Redheart.png" },
  { nome: "Fancy Pants",            img: "imagens/Fancy Pants.png" },
  { nome: "Filthy Rich",            img: "imagens/Filthy Rich.png" },
  { nome: "Fine Line",              img: "imagens/Fine Line.png" },
  { nome: "Fleetfoot",              img: "imagens/Fleetfoot.png" },
  { nome: "Fleur Dis Lee",          img: "imagens/Fleur Dis Lee.png" },
  { nome: "Fleur de Verre",         img: "imagens/Fleur de Verre.png" },
  { nome: "Flurry Heart",           img: "imagens/Flurry Heart.png" },
  { nome: "Gala Appleby",           img: "imagens/Gala Appleby.png" },
  { nome: "Gallant True",           img: "imagens/Gallant True.png" },
  { nome: "Gilda",                  img: "imagens/Gilda.png" },
  { nome: "Gizmo",                  img: "imagens/Gizmo.png" },
  { nome: "Golden Delicious",       img: "imagens/Golden Delicious.png" },
  { nome: "Golden Harvest",         img: "imagens/Golden Harvest.png" },
  { nome: "Goldengrape",            img: "imagens/Goldengrape.png" },
  { nome: "Hayseed Turnip Truck",   img: "imagens/Hayseed Turnip Truck.png" },
  { nome: "Helia",                  img: "imagens/Helia.png" },
  { nome: "Holly Dash",             img: "imagens/Holly Dash.png" },
  { nome: "Hoofbeard",              img: "imagens/Hoofbeard.png" },
  { nome: "Inkwell",                img: "imagens/Inkwell.jpg" },
  { nome: "Iron Will",              img: "imagens/Iron Will.png" },
  { nome: "Ivory",                  img: "imagens/Ivory.png" },
  { nome: "Jeff Letrotski",         img: "imagens/Jeff Letrotski.png" },
  { nome: "Joe",                    img: "imagens/Joe.png" },
  { nome: "Junebug",                img: "imagens/Junebug.png" },
  { nome: "Larry",                  img: "imagens/Larry.png" },
  { nome: "Lemon Hearts",           img: "imagens/Lemon Hearts.png" },
  { nome: "Lemony Gem",             img: "imagens/Lemony Gem.png" },
  { nome: "Lightning Dust",         img: "imagens/Lightning Dust.png" },
  { nome: "Lily Valley",            img: "imagens/Lily Valley.png" },
  { nome: "Liza Doolots",           img: "imagens/Liza Doolots.png" },
  { nome: "Lorde Tirek",            img: "imagens/Lorde Tirek.png" },
  { nome: "Luckette",               img: "imagens/Luckette.png" },
  { nome: "Lucky Clover",           img: "imagens/Lucky Clover.png" },
  { nome: "Lyra Heartstrings",      img: "imagens/Lyra Heartstrings.png" },
  { nome: "Lyrica Lilac",           img: "imagens/Lyrica Lilac.png" },
  { nome: "Masquerade",             img: "imagens/Masquerade.png" },
  { nome: "Matilda",                img: "imagens/Matilda.png" },
  { nome: "Maybelle",               img: "imagens/Maybelle.png" },
  { nome: "Meadow Flower",          img: "imagens/Meadow Flower.jpg" },
  { nome: "Meadow Song",            img: "imagens/Meadow Song.png" },
  { nome: "Merry May",              img: "imagens/Merry May.png" },
  { nome: "Minuette",               img: "imagens/Minuette.png" },
  { nome: "Misty Fly",              img: "imagens/Misty Fly.png" },
  { nome: "Mjölna",                 img: "imagens/Mjölna.png" },
  { nome: "Moon Dancer",            img: "imagens/Moon Dancer.png" },
  { nome: "Múlia Mansa",            img: "imagens/Múlia Mansa.png" },
  { nome: "Neon Lights",            img: "imagens/Neon Lights.png" },
  { nome: "Night Glider",           img: "imagens/Night Glider.png" },
  { nome: "Night Knight",           img: "imagens/Night Knight.png" },
  { nome: "Noteworthy",             img: "imagens/Noteworthy.png" },
  { nome: "Octavia Melody",         img: "imagens/Octavia Melody.png" },
  { nome: "Orange Swirl",           img: "imagens/Orange Swirl.png" },
  { nome: "Owlowiscious",           img: "imagens/Owlowiscious.png" },
  { nome: "Parasol",                img: "imagens/Parasol.png" },
  { nome: "Parish Nandermane",      img: "imagens/Parish Nandermane.png" },
  { nome: "Party Favor",            img: "imagens/Party Favor.png" },
  { nome: "Peachy Pitt",            img: "imagens/Peachy Pitt.png" },
  { nome: "Peachy Sweet",           img: "imagens/Peachy Sweet.png" },
  { nome: "Perfect Pace",           img: "imagens/Perfect Pace.png" },
  { nome: "Pipsqueak",              img: "imagens/Pipsqueak.png" },
  { nome: "Piña Colada",            img: "imagens/Piña Colada.png" },
  { nome: "Ponet",                  img: "imagens/Ponet.png" },
  { nome: "Prim Hemline",           img: "imagens/Prim Hemline.png" },
  { nome: "Prim Posy",              img: "imagens/Prim Posy.png" },
  { nome: "Princesa Amore",         img: "imagens/Princesa Amore.png" },
  { nome: "Princesa Cadance",       img: "imagens/Princesa Cadance.png" },
  { nome: "Princesa Celestia",      img: "imagens/Princesa Celestia.png" },
  { nome: "Princesa Ember",         img: "imagens/Princesa Ember.png" },
  { nome: "Princesa Erroria",       img: "imagens/Princesa Erroria.png" },
  { nome: "Princesa Skystar",       img: "imagens/Princesa Skystar.png" },
  { nome: "Príncipe Blueblood",     img: "imagens/Príncipe Blueblood.png" },
  { nome: "Radiant Hope",           img: "imagens/Radiant Hope.jpg" },
  { nome: "Rainbow Swoop",          img: "imagens/Rainbow Swoop.png" },
  { nome: "Rainbowshine",           img: "imagens/Rainbowshine.png" },
  { nome: "Rainha Chrysalis",       img: "imagens/Rainha Chrysalis.png" },
  { nome: "Rainha Ivona",           img: "imagens/Rainha Ivona.png" },
  { nome: "Randolph",               img: "imagens/Randolph.png" },
  { nome: "Rare Find",              img: "imagens/Rare Find.png" },
  { nome: "Rarity",                 img: "imagens/Rarity.png" },
  { nome: "Red Gala",               img: "imagens/Red Gala.png" },
  { nome: "Rei Leo",                img: "imagens/Rei Leo.png" },
  { nome: "Rei Longhorn",           img: "imagens/Rei Longhorn.jpg" },
  { nome: "Rei Sombra",             img: "imagens/Rei Sombra.png" },
  { nome: "Rei Storm",              img: "imagens/Rei Storm.png" },
  { nome: "Rose",                   img: "imagens/Rose.png" },
  { nome: "Royal Pin",              img: "imagens/Royal Pin.png" },
  { nome: "Royal Riff",             img: "imagens/Royal Riff.png" },
  { nome: "Rubinstein",             img: "imagens/Rubinstein.png" },
  { nome: "Rumble",                 img: "imagens/Rumble.png" },
  { nome: "Sapphire Shores",        img: "imagens/Sapphire Shores.png" },
  { nome: "Sassaflash",             img: "imagens/Sassaflash.png" },
  { nome: "Sassy Saddles",          img: "imagens/Sassy Saddles.png" },
  { nome: "Scootaloo",              img: "imagens/Scootaloo.png" },
  { nome: "Scorpan",                img: "imagens/Scorpan.png" },
  { nome: "Screwy",                 img: "imagens/Screwy.png" },
  { nome: "Sea Swirl",              img: "imagens/Sea Swirl.png" },
  { nome: "Sealed Scroll",          img: "imagens/Sealed Scroll.png" },
  { nome: "Shady Daze",             img: "imagens/Shady Daze.png" },
  { nome: "Shining Armor",          img: "imagens/Shining Armor.png" },
  { nome: "Shoeshine",              img: "imagens/Shoeshine.png" },
  { nome: "Shooting Star",          img: "imagens/Shooting Star.png" },
  { nome: "Silver Spanner",         img: "imagens/Silver Spanner.png" },
  { nome: "Silver Spoon",           img: "imagens/Silver Spoon.png" },
  { nome: "Sir Pony Moore",         img: "imagens/Sir Pony Moore.png" },
  { nome: "Sky Stinger",            img: "imagens/Sky Stinger.png" },
  { nome: "Smolder",                img: "imagens/Smolder.png" },
  { nome: "Snips",                  img: "imagens/Snips.png" },
  { nome: "Soarin",                 img: "imagens/Soarin.png" },
  { nome: "Songbird Serenade",      img: "imagens/Songbird Serenade.png" },
  { nome: "Spitfire",               img: "imagens/Spitfire.png" },
  { nome: "Spoiled Rich",           img: "imagens/Spoiled Rich.png" },
  { nome: "Sprinkle Medley",        img: "imagens/Sprinkle Medley.png" },
  { nome: "Sr. Greenhooves",        img: "imagens/Sr. Greenhooves.png" },
  { nome: "Sr. Waddle",             img: "imagens/Sr. Waddle.png" },
  { nome: "Sra. Harshwhinny",       img: "imagens/Sra. Harshwhinny.png" },
  { nome: "Sra. Peachbottom",       img: "imagens/Sra. Peachbottom.png" },
  { nome: "Star Gazer",             img: "imagens/Star Gazer.png" },
  { nome: "Star Hunter",            img: "imagens/Star Hunter.png" },
  { nome: "Star Swirl, o Barbudo",  img: "imagens/Star Swirl, o Barbudo.png" },
  { nome: "Starry Eyes",            img: "imagens/Starry Eyes.png" },
  { nome: "Stellar Eclipse",        img: "imagens/Stellar Eclipse.png" },
  { nome: "Steven Magnet",          img: "imagens/Steven Magnet.png" },
  { nome: "Strawberry Sunrise",     img: "imagens/Strawberry Sunrise.png" },
  { nome: "Stygian",                img: "imagens/Stygian.png" },
  { nome: "Sugar Belle",            img: "imagens/Sugar Belle.png" },
  { nome: "Sunburst",               img: "imagens/Sunburst.png" },
  { nome: "Sunny Rays",             img: "imagens/Sunny Rays.png" },
  { nome: "Sunshower Raindrops",    img: "imagens/Sunshower Raindrops.png" },
  { nome: "Suri Polomare",          img: "imagens/Suri Polomare.png" },
  { nome: "Surprise",               img: "imagens/Surprise.png" },
  { nome: "Svengallop",             img: "imagens/Svengallop.png" },
  { nome: "Sweetie Belle",          img: "imagens/Sweetie Belle.png" },
  { nome: "Sweetie Drops",          img: "imagens/Sweetie Drops.png" },
  { nome: "Tank",                   img: "imagens/Tank.png" },
  { nome: "Teddie Safari",          img: "imagens/Teddie Safari.png" },
  { nome: "Tempest Shadow",         img: "imagens/Tempest Shadow.png" },
  { nome: "Tender Taps",            img: "imagens/Tender Taps.png" },
  { nome: "Terramar",               img: "imagens/Terramar.png" },
  { nome: "Thorax",                 img: "imagens/Thorax.png" },
  { nome: "Thunderlane",            img: "imagens/Thunderlane.png" },
  { nome: "Tia Applesauce",         img: "imagens/Tia Applesauce.png" },
  { nome: "Tree Hugger",            img: "imagens/Tree Hugger.png" },
  { nome: "Trenderhoof",            img: "imagens/Trenderhoof.png" },
  { nome: "Trixie",                 img: "imagens/Trixie.png" },
  { nome: "Trouble Shoes",          img: "imagens/Trouble Shoes.png" },
  { nome: "Twilight Sky",           img: "imagens/Twilight Sky.png" },
  { nome: "Twinkleshine",           img: "imagens/Twinkleshine.png" },
  { nome: "Twist",                  img: "imagens/Twist.png" },
  { nome: "Vapor Trail",            img: "imagens/Vapor Trail.png" },
  { nome: "Warm Front",             img: "imagens/Warm Front.png" },
  { nome: "Wensley",                img: "imagens/Wensley.png" },
  { nome: "White Lightning",        img: "imagens/White Lightning.png" },
  { nome: "Wind Rider",             img: "imagens/Wind Rider.png" },
  { nome: "Winona",                 img: "imagens/Winona.png" },
  { nome: "Written Script",         img: "imagens/Written Script.png" },
  { nome: "Xerife Silverstar",      img: "imagens/Xerife Silverstar.png" },
  { nome: "Zephyr Breeze",          img: "imagens/Zephyr Breeze.png" },
  { nome: "Zipporwhill",            img: "imagens/Zipporwhill.png" },
];
